// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjhiksvsavtsuejjivhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqaGlrc3ZzYXZ0c3VlamppdmhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MDY1MDYsImV4cCI6MjA2OTE4MjUwNn0.ZSONfRTrQ8Z8WdEoRBIdvgll6yQyPbisOoXsinjV5UA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
